### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by klarose** [a97077088/frida-go#1]
Hello,

This library looks great! I've hacked together my own golang wrappers around frida, but it is not complete. I notice that you've implemented a fairly complete frida wrapper here. I'd love to use it, but I can't really until I know how it is licensed.

Could you maybe add a license to this code? It'd help to give myself and others the confidence to use it. MIT, apache or BSD license would be great.

Thanks.

**Comment by aadog** [comment]
@klarose No, he doesn't need any license. It's just my boring work. Anyone can use it at will. Have a good time, man

**Comment by aadog** [comment]
@klarose He doesn't have any help documents. If you can't write code, please refer to this project https://github.com/a97077088/fd
